#spring.data.mongodb.uri=mongodb://localhost:27017/cloudShare
# application.properties
spring.data.mongodb.auto-index-creation=true

#server.servlet.context-path=/api/v1
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

# CLERK CONFIGURATION
clerk.issuer=${CLERK_ISSUER:https://super-filly-15}
clerk.jwks-url=${CLERK_JWKS_URL:https://super-filly-15}
clerk.webhook.secret=${CLERK_WEBHOOK_SECRET:qpSly4eylPW/k}

#File Upload Configuration
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=25MB

# RAZORPAY CONFIGURATIONS
razorpay.key.id=
razorpay.key.secret=

# MONGO DB ATLAS
spring.data.mongodb.uri=${MONGO_DB_URL:mongodb://localhost:27017/mydb}

# AWS S3 CONFIGURATION
aws.access.key=${AWS_ACCESS_KEY}
aws.secret.key=${AWS_SECRET_KEY}
aws.region=${AWS_REGION}
aws.bucket.name=${AWS_BUCKET_NAME}
